package countries;

public class Countries {
    public static void main(String[] args) {

    }
   public static Country[] countries = {
            new Country("AF", "Afganistan"),
            new Country("AX", "Alandy"),
            new Country("AL", "Albánsko"),
            new Country("DZ", "Alžírsko"),
            new Country("AS", "Americká Samoa"),
            new Country("VI", "Americké Panenské ostrovy"),
            new Country("AD", "Andorra"),
            new Country("AO", "Angola"),
            new Country("AI", "Anguilla"),
            new Country("AQ", "Antarktída"),
            new Country("AG", "Antigua a Barbuda"),
            new Country("AR", "Argentína"),
            new Country("AM", "Arménsko"),
            new Country("AW", "Aruba"),
            new Country("AU", "Austrália"),
            new Country("AZ", "Azerbajdžan"),
            new Country("BS", "Bahamy"),
            new Country("BH", "Bahrajn"),
            new Country("BD", "Bangladéš"),
            new Country("BB", "Barbados"),
            new Country("BE", "Belgicko"),
            new Country("BZ", "Belize"),
            new Country("BJ", "Benin"),
            new Country("BM", "Bermudy"),
            new Country("BT", "Bhután"),
            new Country("BY", "Bielorusko"),
            new Country("BO", "Bolívia"),
            new Country("BQ", "Bonaire, Svätý Eustach a Saba"),
            new Country("BA", "Bosna a Hercegovina"),
            new Country("BW", "Botswana"),
            new Country("BV", "Bouvetov ostrov"),
            new Country("BR", "Brazília"),
            new Country("IO", "Britské indickooceánske územie"),
            new Country("VG", "Britské Panenské ostrovy"),
            new Country("BN", "Brunej"),
            new Country("BG", "Bulharsko"),
            new Country("BF", "Burkina"),
            new Country("BI", "Burundi"),
            new Country("CK", "Cookove ostrovy"),
            new Country("CW", "Curaçao"),
            new Country("CY", "Cyprus"),
            new Country("TD", "Čad"),
            new Country("CZ", "Česko"),
            new Country("ME", "Čierna Hora"),
            new Country("CL", "Čile"),
            new Country("CN", "Čína"),
            new Country("DK", "Dánsko"),
            new Country("DM", "Dominika"),
            new Country("DO", "Dominikánska republika"),
            new Country("DJ", "Džibutsko"),
            new Country("EG", "Egypt"),
            new Country("EC", "Ekvádor"),
            new Country("ER", "Eritrea"),
            new Country("EE", "Estónsko"),
            new Country("ET", "Etiópia"),
            new Country("EU", "Európska únia"),
            new Country("FO", "Faerské ostrovy"),
            new Country("FK", "Falklandy"),
            new Country("FJ", "Fidži"),
            new Country("PH", "Filipíny"),
            new Country("FI", "Fínsko"),
            new Country("FR", "Francúzsko"),
            new Country("GF", "Francúzska Guyana"),
            new Country("PF", "Francúzska Polynézia"),
            new Country("TF", "Francúzske južné územia"),
            new Country("GA", "Gabon"),
            new Country("GM", "Gambia"),
            new Country("GH", "Ghana"),
            new Country("GI", "Gibraltár"),
            new Country("GR", "Grécko"),
            new Country("GD", "Grenada"),
            new Country("GL", "Grónsko"),
            new Country("GE", "Gruzínsko"),
            new Country("GP", "Guadeloupe"),
            new Country("GU", "Guam"),
            new Country("GT", "Guatemala"),
            new Country("GG", "Guernsey"),
            new Country("GN", "Guinea"),
            new Country("GW", "Guinea-Bissau"),
            new Country("GY", "Guyana"),
            new Country("HT", "Haiti"),
            new Country("HM", "Heardov ostrov"),
            new Country("NL", "Holandsko"),
            new Country("AN", "Holandské Antily"),
            new Country("HN", "Honduras"),
            new Country("HK", "Hongkong"),
            new Country("HR", "Chorvátsko"),
            new Country("IN", "India"),
            new Country("ID", "Indonézia"),
            new Country("IR", "Irán"),
            new Country("IQ", "Irak"),
            new Country("IE", "Írsko"),
            new Country("IS", "Island"),
            new Country("IL", "Izrael"),
            new Country("JM", "Jamajka"),
            new Country("JP", "Japonsko"),
            new Country("YE", "Jemen"),
            new Country("JE", "Jersey"),
            new Country("JO", "Jordánsko"),
            new Country("ZA", "Južná Afrika"),
            new Country("GS", "Južná Georgia a Južné Sandwichove ostrovy"),
            new Country("SS", "Južný Sudán"),
            new Country("KY", "Kajmanie ostrovy"),
            new Country("KH", "Kambodža"),
            new Country("CM", "Kamerun"),
            new Country("CA", "Kanada"),
            new Country("CV", "Kapverdy"),
            new Country("QA", "Katar"),
            new Country("KZ", "Kazachstan"),
            new Country("KE", "Keňa"),
            new Country("KG", "Kirgizsko"),
            new Country("KI", "Kiribati"),
            new Country("CC", "Kokosové ostrovy"),
            new Country("CO", "Kolumbia"),
            new Country("KM", "Komory"),
            new Country("CG", "Kongo"),
            new Country("CD", "Konžská demokratická republika"),
            new Country("KP", "Kórejská ľudovodemokratická republika"),
            new Country("KR", "Kórejská republika"),
            new Country("CR", "Kostarika"),
            new Country("CU", "Kuba"),
            new Country("KW", "Kuvajt"),
            new Country("LA", "Laos"),
            new Country("LS", "Lesotho"),
            new Country("LB", "Libanon"),
            new Country("LR", "Libéria"),
            new Country("LY", "Líbya"),
            new Country("LI", "Lichtenštajnsko"),
            new Country("LT", "Litva"),
            new Country("LV", "Lotyšsko"),
            new Country("LU", "Luxembursko"),
            new Country("MO", "Macao"),
            new Country("MK", "Severné Macedónsko"),
            new Country("MG", "Madagaskar"),
            new Country("HU", "Maďarsko"),
            new Country("MY", "Malajzia"),
            new Country("MW", "Malawi"),
            new Country("MV", "Maldivy"),
            new Country("ML", "Mali"),
            new Country("MT", "Malta"),
            new Country("MA", "Maroko"),
            new Country("MH", "Marshallove ostrovy"),
            new Country("MQ", "Martinik"),
            new Country("MU", "Maurícius"),
            new Country("MR", "Mauritánia"),
            new Country("YT", "Mayotte"),
            new Country("UM", "Menšie odľahlé ostrovy USA"),
            new Country("MX", "Mexiko"),
            new Country("FM", "Mikronézia"),
            new Country("MM", "Mjanmarsko"),
            new Country("MD", "Moldavsko"),
            new Country("MC", "Monako"),
            new Country("MN", "Mongolsko"),
            new Country("MS", "Montserrat"),
            new Country("MZ", "Mozambik"),
            new Country("NA", "Namíbia"),
            new Country("NR", "Nauru"),
            new Country("DE", "Nemecko"),
            new Country("NP", "Nepál"),
            new Country("NE", "Niger"),
            new Country("NG", "Nigéria"),
            new Country("NI", "Nikaragua"),
            new Country("NU", "Niue"),
            new Country("NF", "Norfolk"),
            new Country("NO", "Nórsko"),
            new Country("NC", "Nová Kaledónia"),
            new Country("NZ", "Nový Zéland"),
            new Country("OM", "Omán"),
            new Country("IM", "Ostrov Man"),
            new Country("PK", "Pakistan"),
            new Country("PW", "Palau"),
            new Country("PS", "Palestína"),
            new Country("PA", "Panama"),
            new Country("PG", "Papua-Nová Guinea"),
            new Country("PY", "Paraguaj"),
            new Country("PE", "Peru"),
            new Country("PN", "Pitcairnove ostrovy"),
            new Country("CI", "Pobrežie Slonoviny"),
            new Country("PL", "Poľsko"),
            new Country("PR", "Portoriko"),
            new Country("PT", "Portugalsko"),
            new Country("AT", "Rakúsko"),
            new Country("RE", "Réunion"),
            new Country("GQ", "Rovníková Guinea"),
            new Country("RO", "Rumunsko"),
            new Country("RU", "Rusko"),
            new Country("RW", "Rwanda"),
            new Country("MF", "Saint-Martin"),
            new Country("PM", "Saint Pierre a Miquelon"),
            new Country("SV", "Salvádor"),
            new Country("WS", "Samoa"),
            new Country("SM", "San Maríno"),
            new Country("SA", "Saudská Arábia"),
            new Country("SN", "Senegal"),
            new Country("MP", "Severné Mariány"),
            new Country("SC", "Seychely"),
            new Country("SL", "Sierra Leone"),
            new Country("SG", "Singapur"),
            new Country("SX", "Sint Maarten"),
            new Country("SK", "Slovensko"),
            new Country("SI", "Slovinsko"),
            new Country("SO", "Somálsko"),
            new Country("AE", "Spojené arabské emiráty"),
            new Country("GB", "Spojené kráľovstvo"),
            new Country("US", "Spojené štáty"),
            new Country("RS", "Srbsko"),
            new Country("LK", "Srí Lanka"),
            new Country("CF", "Stredoafrická republika"),
            new Country("SD", "Sudán"),
            new Country("SR", "Surinam"),
            new Country("SH", "Svätá Helena"),
            new Country("LC", "Svätá Lucia"),
            new Country("BL", "Svätý Bartolomej"),
            new Country("KN", "Svätý Krištof a Nevis"),
            new Country("ST", "Svätý Tomáš a Princov ostrov"),
            new Country("VC", "Svätý Vincent a Grenadíny"),
            new Country("SZ", "Svazijsko"),
            new Country("SY", "Sýria"),
            new Country("SB", "Šalamúnove ostrovy"),
            new Country("ES", "Španielsko"),
            new Country("SJ", "Špicbergy a Jan Mayen"),
            new Country("CH", "Švajčiarsko"),
            new Country("SE", "Švédsko"),
            new Country("TJ", "Tadžikistan"),
            new Country("TW", "Taiwan"),
            new Country("IT", "Taliansko"),
            new Country("TZ", "Tanzánia"),
            new Country("TH", "Thajsko"),
            new Country("TG", "Togo"),
            new Country("TK", "Tokelau"),
            new Country("TO", "Tonga"),
            new Country("TT", "Trinidad a Tobago"),
            new Country("TN", "Tunisko"),
            new Country("TR", "Turecko"),
            new Country("TM", "Turkménsko"),
            new Country("TC", "Turks a Caicos"),
            new Country("TV", "Tuvalu"),
            new Country("UG", "Uganda"),
            new Country("UA", "Ukrajina"),
            new Country("UY", "Uruguaj"),
            new Country("UZ", "Uzbekistan"),
            new Country("VU", "Vanuatu"),
            new Country("VA", "Vatikán"),
            new Country("VE", "Venezuela"),
            new Country("CX", "Vianočný ostrov"),
            new Country("VN", "Vietnam"),
            new Country("TL", "Východný Timor"),
            new Country("WF", "Wallis a Futuna"),
            new Country("ZM", "Zambia"),
            new Country("EH", "Západná Sahara"),
            new Country("ZW", "Zimbabwe")
    };


}
